- name: packages installed
  yum: name=java-1.{{jdk_version }}.0-openjdk state=present
  when: jdk_version == 8

- name: Symlink java
  file: src=/usr/lib/jvm/jre-openjdk path={{ java_home }} state=link

