- name: setup common packages on Redhat
  include: setup-Redhat.yml
  when: ansible_os_family == 'RedHat'

- name: setup common packages on Debian
  include: setup-Debian.yml
  when: ansible_os_family == 'Debian'


- name: add motd
  copy: src=motd dest=/etc/motd mode=0775